"use client";

import { useState, useMemo, useEffect, useCallback } from "react";
import dynamic from "next/dynamic";
import * as XLSX from "@e965/xlsx";
import {
  BarChart3,
  Calendar,
  CalendarDays,
  ClipboardCheck,
  Download,
  Ship,
  TrendingUp,
  Users,
  type LucideIcon,
} from "lucide-react";
import { DashboardData, DashboardSummary, PeriodType } from "@/types";
import KPICards from "@/components/dashboard/KPICards";
import { KPICard, type KPITone, Button } from "@/components/cosmic";
import DataTable from "@/components/dashboard/DataTable";
import AlertsPanel from "@/components/dashboard/AlertsPanel";
import { loadFromStorage } from "@/components/dashboard/ExcelParser";
import { getThroughputByHour } from "@/services/reportService";
import DateFilter, { DateFilterValue } from "@/components/dashboard/DateFilter";
import DateRangePicker, {
  DateRange,
} from "@/components/dashboard/DateRangePicker";
import DrilldownModal from "@/components/dashboard/DrilldownModal";
import {
  useDbStatus,
  useDailyData,
  useMonthlyData,
  useYoYComparison,
  useYoYComparisonQuarter,
  useYoYComparisonYear,
} from "@/lib/hooks";
import { getCurrentYear } from "@/lib/db";
import apiClient, { type ExecutiveKpis } from "@/lib/apiClient";
import { useAuth } from "@/components/AuthProvider";

// Dynamic imports for charts (disable SSR to avoid Recharts warning)
const BarChart = dynamic(() => import("@/components/dashboard/BarChart"), {
  ssr: false,
});
const PieChart = dynamic(() => import("@/components/dashboard/PieChart"), {
  ssr: false,
});
const YoYComparisonChart = dynamic(
  () => import("@/components/dashboard/YoYComparisonChart"),
  { ssr: false }
);
const CumulativeChart = dynamic(
  () => import("@/components/dashboard/CumulativeChart"),
  { ssr: false }
);
const HourlyChart = dynamic(
  () => import("@/components/dashboard/HourlyChart"),
  { ssr: false }
);
const CargoDonut = dynamic(
  () => import("@/components/dashboard/CargoDonut"),
  { ssr: false }
);

type DashboardMode = "daily" | "monthly";

// Module-level constant (not inside component to avoid re-creation on each render)
const DAILY_PAGE_SIZE = 10;

function todayIsoDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function ExecutiveKpiPanel() {
  const { session } = useAuth();
  const [date, setDate] = useState(todayIsoDate);
  const [data, setData] = useState<ExecutiveKpis | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [downloadError, setDownloadError] = useState<string | null>(null);
  const [downloading, setDownloading] = useState(false);
  const [downloadingExcel, setDownloadingExcel] = useState(false);

  useEffect(() => {
    if (session?.role !== "admin" || session.mode === "local-dev") return;

    let cancelled = false;

    const load = async () => {
      const result = await apiClient.getExecutiveKpis(date);
      if (cancelled) return;

      if (result.error || !result.data) {
        setError(result.error || "Không tải được KPI lãnh đạo");
        setData(null);
        return;
      }

      setError(null);
      setData(result.data);
    };

    void load();
    const timer = window.setInterval(() => {
      void load();
    }, 60_000);

    return () => {
      cancelled = true;
      window.clearInterval(timer);
    };
  }, [date, session?.mode, session?.role]);

  if (session?.role !== "admin" || session.mode === "local-dev") return null;

  const handleDownloadReport = async () => {
    setDownloading(true);
    setDownloadError(null);
    const result = await apiClient.downloadExecutiveReportCsv(date);
    setDownloading(false);

    if (result.error || !result.data) {
      setDownloadError(result.error || "Không tải được báo cáo KPI");
      return;
    }

    const url = window.URL.createObjectURL(result.data);
    const link = document.createElement("a");
    link.href = url;
    link.download = `ttport-executive-kpi-${date}.csv`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
  };

  const handleDownloadExcelReport = async () => {
    setDownloadingExcel(true);
    setDownloadError(null);
    const result = await apiClient.getExecutiveReportPack(date);
    setDownloadingExcel(false);

    if (result.error || !result.data) {
      setDownloadError(result.error || "Không tải được báo cáo KPI Excel");
      return;
    }

    const report = result.data;
    const summaryRows = [
      { Chỉ_số: "Generated At", Giá_trị: report.generatedAt },
      { Chỉ_số: "Generated By", Giá_trị: report.generatedBy },
      { Chỉ_số: "Start Date", Giá_trị: report.period.startDate },
      { Chỉ_số: "End Date", Giá_trị: report.period.endDate },
      { Chỉ_số: "Total In", Giá_trị: report.summary.total_in },
      { Chỉ_số: "Total Out", Giá_trị: report.summary.total_out },
      { Chỉ_số: "Total CFS", Giá_trị: report.summary.total_cfs },
      { Chỉ_số: "Total Moves", Giá_trị: report.summary.total_moves },
      { Chỉ_số: "Vessel Moves", Giá_trị: report.summary.vessel_moves },
      { Chỉ_số: "Vessel TEUs", Giá_trị: report.summary.vessel_teus },
      { Chỉ_số: "Report Count", Giá_trị: report.summary.report_count },
      { Chỉ_số: "Leave Requests", Giá_trị: report.summary.leave_requests },
    ];

    const detailRows = report.rows.map((row) => ({
      Ngày: row.date,
      "Vào": row.total_in,
      "Ra": row.total_out,
      CFS: row.total_cfs,
      "Tổng biến động": row.total_moves,
      "Moves tàu": row.vessel_moves,
      TEUs: row.vessel_teus,
      "Số báo cáo": row.report_count,
      "Nghỉ phép": row.leave_requests,
    }));

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(
      workbook,
      XLSX.utils.json_to_sheet(summaryRows),
      "Summary"
    );
    XLSX.utils.book_append_sheet(
      workbook,
      XLSX.utils.json_to_sheet(detailRows),
      "Daily Detail"
    );
    XLSX.writeFile(workbook, `ttport-executive-kpi-${date}.xlsx`);
  };

  if (error) {
    return (
      <div className="mb-6 rounded-xl border border-yellow-400/30 bg-yellow-400/10 p-4 text-sm text-yellow-200">
        {error}
      </div>
    );
  }

  const cards: {
    label: string;
    value: number;
    suffix?: string;
    hint: string;
    Icon: LucideIcon;
    tone: KPITone;
  }[] = [
    {
      label: "Sản lượng ngày",
      value: data?.daily.totalMoves ?? 0,
      hint: `Vào ${data?.daily.totalIn ?? 0} / Ra ${data?.daily.totalOut ?? 0}`,
      Icon: BarChart3,
      tone: "accent",
    },
    {
      label: "Lũy kế tháng",
      value: data?.monthToDate.totalMoves ?? 0,
      hint: `${data?.monthToDate.reportCount ?? 0} báo cáo đã nộp`,
      Icon: TrendingUp,
      tone: "success",
    },
    {
      label: "Tàu / TEUs ngày",
      value: data?.daily.vesselMoves ?? 0,
      hint: `${data?.daily.vesselTeus ?? 0} TEUs`,
      Icon: Ship,
      tone: "info",
    },
    {
      label: "Nhân sự hoạt động",
      value: data?.workforce.activeEmployees ?? 0,
      hint: `${data?.workforce.departments ?? 0} bộ phận / ${data?.workforce.shifts ?? 0} ca`,
      Icon: Users,
      tone: "warning",
    },
    {
      label: "Hoàn tất báo cáo",
      value: data?.daily.reportCompletionRate ?? 0,
      suffix: "%",
      hint: `${data?.daily.leaveRequests ?? 0} đơn nghỉ phép`,
      Icon: ClipboardCheck,
      tone: "success",
    },
  ];

  return (
    <section className="mb-6">
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-[var(--color-text-muted)]">
            KPI lãnh đạo
          </p>
          <h3 className="mt-0.5 text-xl font-semibold text-[var(--color-text-primary)]">
            Tổng quan ngày, tháng và nhân sự
          </h3>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <input
            type="date"
            aria-label="Chọn ngày"
            value={date}
            onChange={(event) => setDate(event.target.value)}
            className="cvf-input h-9 rounded-lg px-3 text-sm"
          />
          <Button
            variant="secondary"
            icon={Download}
            onClick={handleDownloadReport}
            disabled={downloading}
          >
            {downloading ? "Đang tải" : "Tải KPI CSV"}
          </Button>
          <Button
            variant="primary"
            icon={Download}
            onClick={handleDownloadExcelReport}
            disabled={downloadingExcel}
          >
            {downloadingExcel ? "Đang tạo" : "Tải KPI Excel"}
          </Button>
        </div>
      </div>

      {downloadError && (
        <div className="mb-3 rounded-lg border border-yellow-400/30 bg-yellow-400/10 p-3 text-sm text-yellow-200">
          {downloadError}
        </div>
      )}

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
        {cards.map((card) => (
          <KPICard
            key={card.label}
            icon={card.Icon}
            label={card.label}
            value={`${card.value.toLocaleString("vi-VN")}${card.suffix ?? ""}`}
            tone={card.tone}
            hint={card.hint}
          />
        ))}
      </div>
    </section>
  );
}

const PERIOD_TABS: {
  key: PeriodType;
  label: string;
  icon: LucideIcon;
  mode: DashboardMode;
}[] = [
  { key: "day", label: "Ngày", icon: Calendar, mode: "daily" },
  { key: "month", label: "Tháng", icon: CalendarDays, mode: "monthly" },
  { key: "year", label: "Năm", icon: BarChart3, mode: "monthly" },
  { key: "cumulative", label: "Lũy Tiến", icon: TrendingUp, mode: "monthly" },
];

// Demo data
const DEMO_MONTHLY: DashboardData[] = [
  {
    id: "1",
    period: "T01",
    periodType: "month",
    label: "T01",
    tongBienDong: 5178,
    tongCont: 4950,
    xe: { ha: 120, giao: 230, fullCfs: 50, emptyCfs: 30, total: 4102 },
    xalan: { ha: 80, giao: 60, fullCfs: 20, emptyCfs: 10, total: 1076 },
    cfs: { full: 350, empty: 120 },
  },
  {
    id: "2",
    period: "T02",
    periodType: "month",
    label: "T02",
    tongBienDong: 4890,
    tongCont: 4650,
    xe: { ha: 110, giao: 220, fullCfs: 45, emptyCfs: 28, total: 3876 },
    xalan: { ha: 75, giao: 55, fullCfs: 18, emptyCfs: 9, total: 1014 },
    cfs: { full: 320, empty: 110 },
    comparison: { previousValue: 5178, changePercent: -5.6, trend: "down" },
  },
  {
    id: "3",
    period: "T03",
    periodType: "month",
    label: "T03",
    tongBienDong: 5320,
    tongCont: 5100,
    xe: { ha: 130, giao: 250, fullCfs: 55, emptyCfs: 32, total: 4256 },
    xalan: { ha: 85, giao: 65, fullCfs: 22, emptyCfs: 12, total: 1064 },
    cfs: { full: 380, empty: 130 },
    comparison: { previousValue: 4890, changePercent: 8.8, trend: "up" },
  },
  {
    id: "4",
    period: "T04",
    periodType: "month",
    label: "T04",
    tongBienDong: 5150,
    tongCont: 4900,
    xe: { ha: 125, giao: 240, fullCfs: 52, emptyCfs: 30, total: 4120 },
    xalan: { ha: 82, giao: 62, fullCfs: 21, emptyCfs: 11, total: 1030 },
    cfs: { full: 360, empty: 125 },
    comparison: { previousValue: 5320, changePercent: -3.2, trend: "down" },
  },
  {
    id: "5",
    period: "T05",
    periodType: "month",
    label: "T05",
    tongBienDong: 5480,
    tongCont: 5250,
    xe: { ha: 135, giao: 260, fullCfs: 58, emptyCfs: 34, total: 4384 },
    xalan: { ha: 88, giao: 68, fullCfs: 24, emptyCfs: 13, total: 1096 },
    cfs: { full: 400, empty: 140 },
    comparison: { previousValue: 5150, changePercent: 6.4, trend: "up" },
  },
  {
    id: "6",
    period: "T06",
    periodType: "month",
    label: "T06",
    tongBienDong: 5302,
    tongCont: 5080,
    xe: { ha: 128, giao: 248, fullCfs: 54, emptyCfs: 31, total: 4242 },
    xalan: { ha: 84, giao: 64, fullCfs: 22, emptyCfs: 11, total: 1060 },
    cfs: { full: 375, empty: 132 },
    comparison: { previousValue: 5480, changePercent: -3.2, trend: "down" },
  },
];

const DEMO_DAILY: DashboardData[] = [
  {
    id: "d1",
    period: "01",
    periodType: "day",
    label: "Ngày 01",
    tongBienDong: 145,
    tongCont: 145,
    xe: { ha: 40, giao: 52, fullCfs: 5, emptyCfs: 3, total: 102 },
    xalan: { ha: 15, giao: 10, fullCfs: 3, emptyCfs: 2, total: 43 },
    cfs: { full: 24, empty: 10 },
  },
  {
    id: "d2",
    period: "02",
    periodType: "day",
    label: "Ngày 02",
    tongBienDong: 130,
    tongCont: 130,
    xe: { ha: 35, giao: 45, fullCfs: 4, emptyCfs: 2, total: 90 },
    xalan: { ha: 12, giao: 8, fullCfs: 2, emptyCfs: 1, total: 40 },
    cfs: { full: 20, empty: 8 },
    comparison: { previousValue: 145, changePercent: -10.3, trend: "down" },
  },
  {
    id: "d3",
    period: "03",
    periodType: "day",
    label: "Ngày 03",
    tongBienDong: 204,
    tongCont: 204,
    xe: { ha: 55, giao: 67, fullCfs: 8, emptyCfs: 5, total: 154 },
    xalan: { ha: 20, giao: 15, fullCfs: 5, emptyCfs: 3, total: 50 },
    cfs: { full: 35, empty: 15 },
    comparison: { previousValue: 130, changePercent: 56.9, trend: "up" },
  },
  {
    id: "d4",
    period: "04",
    periodType: "day",
    label: "Ngày 04",
    tongBienDong: 176,
    tongCont: 176,
    xe: { ha: 48, giao: 58, fullCfs: 6, emptyCfs: 4, total: 126 },
    xalan: { ha: 18, giao: 12, fullCfs: 4, emptyCfs: 2, total: 50 },
    cfs: { full: 28, empty: 12 },
    comparison: { previousValue: 204, changePercent: -13.7, trend: "down" },
  },
  {
    id: "d5",
    period: "05",
    periodType: "day",
    label: "Ngày 05",
    tongBienDong: 189,
    tongCont: 189,
    xe: { ha: 52, giao: 62, fullCfs: 7, emptyCfs: 4, total: 139 },
    xalan: { ha: 19, giao: 13, fullCfs: 4, emptyCfs: 3, total: 50 },
    cfs: { full: 30, empty: 13 },
    comparison: { previousValue: 176, changePercent: 7.4, trend: "up" },
  },
];

export default function DashboardPage() {
  const [dashboardMode, setDashboardMode] = useState<DashboardMode>("monthly");
  const [activeTab, setActiveTab] = useState<PeriodType>("month");
  const [dailyData, setDailyData] = useState<DashboardData[]>([]);
  const [monthlyData, setMonthlyData] = useState<DashboardData[]>([]);
  const [hasRealData, setHasRealData] = useState({
    daily: false,
    monthly: false,
  });

  // Hourly throughput (today's date)
  const [hourlyData, setHourlyData] = useState<{ hour: number; teus: number }[]>([]);

  // Pagination state for daily view
  const [dailyPage, setDailyPage] = useState(1);

  // Date filter state
  const [dateFilter, setDateFilter] = useState<DateFilterValue>({
    year: getCurrentYear(),
  });

  // Date range state for advanced filtering
  const [dateRange, setDateRange] = useState<DateRange>({
    startDate: null,
    endDate: null,
  });

  // Drilldown state for modal
  const [drilldown, setDrilldown] = useState<{
    isOpen: boolean;
    month: number;
    label: string;
  }>({
    isOpen: false,
    month: 0,
    label: "",
  });

  // Handle drill-down click (for monthly data)
  const handleDrilldown = useCallback((month: number, label: string) => {
    setDrilldown({ isOpen: true, month, label });
  }, []);

  const closeDrilldown = useCallback(() => {
    setDrilldown((prev) => ({ ...prev, isOpen: false }));
  }, []);

  // Handle filter change - reset page when filter changes
  const handleFilterChange = useCallback((filter: DateFilterValue) => {
    setDateFilter(filter);
    setDailyPage(1); // Reset to page 1
    setDateRange({ startDate: null, endDate: null }); // Clear date range
  }, []);

  // Load data from IndexedDB using hooks
  const dbDailyData = useDailyData(dateFilter.year, dateFilter.month);
  const dbMonthlyData = useMonthlyData(dateFilter.year);
  const dbStatus = useDbStatus();

  // YoY Comparison data
  const yoyMonthData = useYoYComparison(
    dateFilter.month || new Date().getMonth() + 1,
    3
  );
  const yoyQuarterData = useYoYComparisonQuarter(dateFilter.quarter || 1, 3);
  const yoyYearData = useYoYComparisonYear(3);

  // Load hourly data on mount
  useEffect(() => {
    setHourlyData(getThroughputByHour(todayIsoDate()));
  }, []);

  // Load from localStorage on mount (fallback)
  useEffect(() => {
    const savedDaily = loadFromStorage("daily");
    const savedMonthly = loadFromStorage("monthly");

    if (savedDaily && savedDaily.length > 0) {
      setDailyData(savedDaily);
      setHasRealData((prev) => ({ ...prev, daily: true }));
    } else {
      setDailyData(DEMO_DAILY);
    }

    if (savedMonthly && savedMonthly.length > 0) {
      setMonthlyData(savedMonthly);
      setHasRealData((prev) => ({ ...prev, monthly: true }));
    } else {
      setMonthlyData(DEMO_MONTHLY);
    }
  }, []);

  // Determine if using DB data
  const hasDbData = dbStatus?.hasData || false;

  // Get current data based on mode - prefer IndexedDB if available
  const currentData = useMemo(() => {
    if (dashboardMode === "daily") {
      // Use DB data if available
      if (dbDailyData && dbDailyData.length > 0) {
        // Convert DB format to DashboardData format
        return dbDailyData.map((d) => ({
          id: d.id?.toString() || `day-${d.day}`,
          period: d.day.toString().padStart(2, "0"),
          periodType: "day" as PeriodType,
          label: `Ngày ${d.day.toString().padStart(2, "0")}`,
          tongBienDong: d.total,
          tongCont: d.total,
          xe: {
            ha: d.xe_ha,
            giao: d.xe_giao,
            // xe_dh = đóng hàng (full CFS), xe_rr = rút ruột (empty CFS)
            // Fallback: split xe_cfs evenly if detail fields not available
            fullCfs: d.xe_dh ?? Math.floor(d.xe_cfs / 2),
            emptyCfs: d.xe_rr ?? Math.ceil(d.xe_cfs / 2),
            total: d.xe_total,
          },
          xalan: {
            ha: d.xalan_ha,
            giao: d.xalan_giao,
            fullCfs: d.xalan_dh ?? Math.floor(d.xalan_cfs / 2),
            emptyCfs: d.xalan_rr ?? Math.ceil(d.xalan_cfs / 2),
            total: d.xalan_total,
          },
          cfs: {
            // total_cfs is the combined CFS total; split if detail not available
            full: (d.xe_dh ?? 0) + (d.xalan_dh ?? 0) || Math.floor(d.total_cfs / 2),
            empty: (d.xe_rr ?? 0) + (d.xalan_rr ?? 0) || Math.ceil(d.total_cfs / 2),
          },
        }));
      }
      return dailyData;
    } else {
      // Monthly mode - use DB data if available
      if (dbMonthlyData && dbMonthlyData.length > 0) {
        // Filter by month/quarter if specified
        let filtered = dbMonthlyData;
        if (dateFilter.month) {
          filtered = filtered.filter((d) => d.month === dateFilter.month);
        }
        if (dateFilter.quarter) {
          filtered = filtered.filter((d) => d.quarter === dateFilter.quarter);
        }

        return filtered.map((d) => ({
          id: d.id?.toString() || `month-${d.year}-${d.month}`,
          period: `T${d.month.toString().padStart(2, "0")}`,
          periodType: "month" as PeriodType,
          label:
            dateFilter.month || dateFilter.quarter
              ? `T${d.month.toString().padStart(2, "0")}/${d.year}`
              : `T${d.month.toString().padStart(2, "0")}`,
          tongBienDong: d.total,
          tongCont: d.total,
          xe: {
            ha: d.xe_ha,
            giao: d.xe_giao,
            // xe_cfs is total CFS; monthly summary doesn't have dh/rr breakdown
            fullCfs: Math.floor(d.xe_cfs / 2),
            emptyCfs: Math.ceil(d.xe_cfs / 2),
            total: d.xe_total,
          },
          xalan: {
            ha: d.xalan_ha,
            giao: d.xalan_giao,
            fullCfs: Math.floor(d.xalan_cfs / 2),
            emptyCfs: Math.ceil(d.xalan_cfs / 2),
            total: d.xalan_total,
          },
          cfs: {
            full: Math.floor(d.total_cfs / 2),
            empty: Math.ceil(d.total_cfs / 2),
          },
        }));
      }
      // Fallback to localStorage - filter by selected year if possible
      // Note: localStorage data doesn't have year info, so return all
      return monthlyData;
    }
  }, [
    dashboardMode,
    dailyData,
    monthlyData,
    dbDailyData,
    dbMonthlyData,
    dateFilter,
  ]);

  const isUsingDemo =
    !hasDbData &&
    (dashboardMode === "daily" ? !hasRealData.daily : !hasRealData.monthly);

  // Filter data by period type (for tabs)
  const filteredData = useMemo(() => {
    if (dashboardMode === "daily") {
      return currentData;
    }
    if (activeTab === "cumulative") {
      return currentData.filter(
        (d) => d.periodType === "cumulative" || d.periodType === "year"
      );
    }
    return currentData.filter((d) => d.periodType === activeTab);
  }, [currentData, activeTab, dashboardMode]);

  // Calculate summary
  const summary: DashboardSummary = useMemo(() => {
    const total = filteredData.reduce(
      (acc, d) => ({
        xeTotal: acc.xeTotal + d.xe.total,
        xalanTotal: acc.xalanTotal + d.xalan.total,
      }),
      { xeTotal: 0, xalanTotal: 0 }
    );

    const grandTotal = total.xeTotal + total.xalanTotal;

    return {
      totalIn: filteredData.reduce((acc, d) => acc + d.xe.ha + d.xalan.ha, 0),
      totalOut: filteredData.reduce(
        (acc, d) => acc + d.xe.giao + d.xalan.giao,
        0
      ),
      xeTotal: total.xeTotal,
      xalanTotal: total.xalanTotal,
      xePercent: grandTotal > 0 ? (total.xeTotal / grandTotal) * 100 : 0,
      xalanPercent: grandTotal > 0 ? (total.xalanTotal / grandTotal) * 100 : 0,
    };
  }, [filteredData]);

  // Cargo classification breakdown (Hạ / Giao / CFS In / CFS Out)
  const cargoSummary = useMemo(() => ({
    ha:     filteredData.reduce((acc, d) => acc + d.xe.ha     + d.xalan.ha,     0),
    giao:   filteredData.reduce((acc, d) => acc + d.xe.giao   + d.xalan.giao,   0),
    cfsIn:  filteredData.reduce((acc, d) => acc + d.xe.fullCfs  + d.xalan.fullCfs,  0),
    cfsOut: filteredData.reduce((acc, d) => acc + d.xe.emptyCfs + d.xalan.emptyCfs, 0),
  }), [filteredData]);

  // Chart data - paginate for daily mode
  const chartData = useMemo(() => {
    if (dashboardMode === "daily") {
      // Apply pagination for daily
      const start = (dailyPage - 1) * DAILY_PAGE_SIZE;
      const end = start + DAILY_PAGE_SIZE;
      const paginatedData = filteredData.slice(start, end);
      return paginatedData.map((d) => ({
        label: d.label,
        xe: d.xe.total,
        xalan: d.xalan.total,
      }));
    }
    // No pagination for monthly
    return filteredData.map((d) => ({
      label: d.label,
      xe: d.xe.total,
      xalan: d.xalan.total,
    }));
  }, [filteredData, dashboardMode, dailyPage]);

  // Pagination info for daily
  const dailyPagination = useMemo(() => {
    if (dashboardMode !== "daily") return null;
    const totalItems = filteredData.length;
    const totalPages = Math.ceil(totalItems / DAILY_PAGE_SIZE);
    return { totalItems, totalPages, currentPage: dailyPage };
  }, [dashboardMode, filteredData.length, dailyPage]);

  // Data for cumulative chart (needs xe_total, xalan_total, total format)
  const cumulativeChartData = useMemo(() => {
    return filteredData.map((d) => ({
      label: d.label,
      xe_total: d.xe.total,
      xalan_total: d.xalan.total,
      total: d.xe.total + d.xalan.total,
    }));
  }, [filteredData]);

  // Switch dashboard mode - reset page
  const handleModeChange = (mode: DashboardMode) => {
    setDashboardMode(mode);
    setActiveTab(mode === "daily" ? "day" : "month");
    setDailyPage(1); // Reset page when switching mode
  };

  // Available tabs for current mode
  const availableTabs = PERIOD_TABS.filter((t) => t.mode === dashboardMode);
  const periodContext =
    dashboardMode === "daily"
      ? dateFilter.month
        ? `Ngày / T${dateFilter.month.toString().padStart(2, "0")}/${dateFilter.year}`
        : `Ngày / ${dateFilter.year}`
      : dateFilter.month
        ? `T${dateFilter.month.toString().padStart(2, "0")}/${dateFilter.year}`
        : dateFilter.quarter
          ? `Q${dateFilter.quarter}/${dateFilter.year}`
          : `${dateFilter.year}`;

  return (
    <div>
      <div>
        <div className="mb-5 flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
          <div>
            <p className="text-sm font-medium text-[var(--color-text-secondary)]">
              Bức tranh vận hành container
            </p>
            <h2 className="text-2xl font-semibold text-[var(--color-text-primary)]">
              Theo dõi biến động vào/ra
            </h2>
          </div>
          <span className="w-fit rounded-full border border-[var(--color-border)] bg-[var(--color-accent-dim)] px-3 py-1.5 text-sm font-semibold text-[var(--color-text-primary)]">
            {periodContext}
          </span>
        </div>

        <ExecutiveKpiPanel />

        <AlertsPanel date={todayIsoDate()} />

        {/* Dashboard Mode Switcher */}
        <div className="flex items-center gap-4 mb-4">
          <span className="text-[var(--color-text-secondary)] text-sm">Chọn Dashboard:</span>
          <div className="flex rounded-xl bg-[var(--color-surface)] p-1 ring-1 ring-[var(--color-border)]">
            <button
              onClick={() => handleModeChange("daily")}
              className={`px-4 py-2 rounded-lg transition-all font-medium ${
                dashboardMode === "daily"
                  ? "bg-[var(--color-accent)] text-white shadow-lg"
                  : "text-[var(--color-text-secondary)] hover:text-white"
              }`}
            >
              Biến Động Ngày
            </button>
            <button
              onClick={() => handleModeChange("monthly")}
              className={`px-4 py-2 rounded-lg transition-all font-medium ${
                dashboardMode === "monthly"
                  ? "bg-[var(--color-accent)] text-white shadow-lg"
                  : "text-[var(--color-text-secondary)] hover:text-white"
              }`}
            >
              Biến Động Tháng/Năm
            </button>
          </div>

          {/* Data status */}
          <span
            className={`text-xs px-2 py-1 rounded ${
              isUsingDemo
                ? "bg-amber-900/50 text-amber-400"
                : "bg-green-900/50 text-green-400"
            }`}
          >
            {isUsingDemo ? "⚠️ Demo" : "✓ Dữ liệu thực"}
          </span>
        </div>

        {/* Advanced Filters Row */}
        <div className="flex flex-wrap items-center gap-3 mb-4">
          {/* Date Range Picker */}
          <DateRangePicker value={dateRange} onChange={setDateRange} />
        </div>

        {/* Period Tabs (only for monthly mode) */}
        {dashboardMode === "monthly" && (
          <div className="flex flex-wrap gap-2 mb-6 bg-gray-800/50 p-2 rounded-xl">
            {availableTabs.map((tab) => {
              const Icon = tab.icon;
              return (
                <button
                  key={tab.key}
                  onClick={() => setActiveTab(tab.key)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-lg transition-all ${
                    activeTab === tab.key
                      ? "bg-[var(--color-accent)] text-white shadow-lg"
                      : "bg-[var(--color-bg)]/50 text-[var(--color-text-secondary)] hover:bg-[var(--color-elevated)] hover:text-white"
                  }`}
                >
                  <Icon className="h-4 w-4" aria-hidden="true" />
                  <span className="hidden sm:inline">{tab.label}</span>
                </button>
              );
            })}
          </div>
        )}

        {/* Date Filter */}
        <DateFilter onFilterChange={handleFilterChange} mode={dashboardMode} />

        {/* No Data Warning */}
        {filteredData.length === 0 && hasDbData && (
          <div className="mb-6 p-4 bg-amber-900/30 border border-amber-600/50 rounded-xl flex items-center gap-3">
            <span className="text-2xl">⚠️</span>
            <div>
              <p className="text-amber-400 font-medium">
                Không có dữ liệu cho thời gian đã chọn
              </p>
              <p className="text-amber-300/70 text-sm">
                Vui lòng kiểm tra lại bộ lọc hoặc upload thêm dữ liệu.
                {dateFilter.month &&
                  ` Tháng ${dateFilter.month}/${dateFilter.year} chưa có dữ liệu.`}
                {dateFilter.quarter &&
                  ` Quý ${dateFilter.quarter}/${dateFilter.year} chưa có dữ liệu.`}
                {!dateFilter.month &&
                  !dateFilter.quarter &&
                  ` Năm ${dateFilter.year} chưa có dữ liệu.`}
              </p>
            </div>
          </div>
        )}

        {/* KPI Cards */}
        <div className="mb-6">
          <KPICards summary={summary} />
        </div>

        {/* Charts Row */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
          {/* Bar Chart - 2/3 width */}
          <div className="lg:col-span-2">
            <BarChart
              data={chartData}
              title={`📊 Biến Động theo ${
                dashboardMode === "daily"
                  ? "Ngày"
                  : availableTabs.find((t) => t.key === activeTab)?.label ||
                    "Thời gian"
              }`}
            />
          </div>

          {/* Pie + CargoDonut stacked - 1/3 width */}
          <div className="flex flex-col gap-4">
            <PieChart xe={summary.xeTotal} xalan={summary.xalanTotal} />
            <CargoDonut
              ha={cargoSummary.ha}
              giao={cargoSummary.giao}
              cfsIn={cargoSummary.cfsIn}
              cfsOut={cargoSummary.cfsOut}
            />
          </div>
        </div>

        {/* Hourly throughput — daily mode only */}
        {dashboardMode === "daily" && (
          <div className="mb-6">
            <HourlyChart data={hourlyData} />
          </div>
        )}

        {/* Cumulative Chart - shows when Lũy Tiến tab is active */}
        {activeTab === "cumulative" && cumulativeChartData.length > 0 && (
          <div className="mb-6">
            <CumulativeChart
              data={cumulativeChartData}
              title={`Lũy Tiến theo Tháng`}
            />
          </div>
        )}

        {/* YoY Comparison Charts */}
        {dashboardMode === "monthly" && (
          <div className="mb-6">
            {/* YoY for specific month */}
            {dateFilter.month && (
              <YoYComparisonChart
                data={yoyMonthData}
                month={dateFilter.month}
                title={`📈 So sánh cùng kỳ Tháng ${dateFilter.month} (3 năm)`}
              />
            )}

            {/* YoY for specific quarter */}
            {!dateFilter.month &&
              dateFilter.quarter &&
              yoyQuarterData &&
              yoyQuarterData.length > 0 && (
                <div className="bg-gray-800/50 rounded-xl p-6">
                  <h3 className="text-lg font-semibold text-white mb-4">
                    📊 So sánh Quý {dateFilter.quarter} (3 năm gần nhất)
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    {yoyQuarterData.map((item) => (
                      <div
                        key={item.year}
                        className="bg-gray-900/50 rounded-lg p-4 text-center"
                      >
                        <p className="text-gray-400 text-sm">Năm {item.year}</p>
                        <p className="text-2xl font-bold text-white">
                          {item.total.toLocaleString()}
                        </p>
                        <div className="flex justify-center gap-4 mt-2 text-sm">
                          <span className="text-orange-400">
                            XE: {item.xe_total.toLocaleString()}
                          </span>
                          <span className="text-purple-400">
                            XALAN: {item.xalan_total.toLocaleString()}
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

            {/* YoY for full year comparison */}
            {!dateFilter.month &&
              !dateFilter.quarter &&
              yoyYearData &&
              yoyYearData.length > 0 && (
                <div className="bg-gray-800/50 rounded-xl p-6">
                  <h3 className="text-lg font-semibold text-white mb-4">
                    📊 So sánh Năm (3 năm gần nhất)
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    {yoyYearData.map((item, idx) => {
                      const prevItem = yoyYearData[idx - 1];
                      const change = prevItem
                        ? ((item.total - prevItem.total) / prevItem.total) * 100
                        : 0;
                      return (
                        <div
                          key={item.year}
                          className="bg-gray-900/50 rounded-lg p-4 text-center"
                        >
                          <p className="text-gray-400 text-sm">
                            Năm {item.year}
                          </p>
                          <p className="text-2xl font-bold text-white">
                            {item.total.toLocaleString()}
                          </p>
                          {prevItem && (
                            <p
                              className={`text-sm mt-1 ${
                                change >= 0 ? "text-green-400" : "text-red-400"
                              }`}
                            >
                              {change >= 0 ? "▲" : "▼"}{" "}
                              {Math.abs(change).toFixed(1)}% so với{" "}
                              {item.year - 1}
                            </p>
                          )}
                          <div className="flex justify-center gap-4 mt-2 text-sm">
                            <span className="text-orange-400">
                              XE: {item.xe_total.toLocaleString()}
                            </span>
                            <span className="text-purple-400">
                              XALAN: {item.xalan_total.toLocaleString()}
                            </span>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}
          </div>
        )}

        {/* Pagination for Daily Mode */}
        {dailyPagination && dailyPagination.totalPages > 1 && (
          <div className="mb-4 flex items-center justify-center gap-3">
            <span className="text-gray-400 text-sm">
              Trang {dailyPagination.currentPage}/{dailyPagination.totalPages}(
              {dailyPagination.totalItems} ngày)
            </span>
            <div className="flex gap-2">
              <button
                onClick={() => setDailyPage((p) => Math.max(1, p - 1))}
                disabled={dailyPage === 1}
                className="px-3 py-1.5 rounded bg-gray-700 text-white text-sm
                                         disabled:opacity-50 disabled:cursor-not-allowed
                                         hover:bg-gray-600 transition-colors"
              >
                ‹ Trước
              </button>
              {Array.from(
                { length: dailyPagination.totalPages },
                (_, i) => i + 1
              ).map((page) => (
                <button
                  key={page}
                  onClick={() => setDailyPage(page)}
                  className={`px-3 py-1.5 rounded text-sm font-medium transition-colors
                                              ${
                                                dailyPage === page
                                                  ? "bg-blue-600 text-white"
                                                  : "bg-gray-700 text-gray-300 hover:bg-gray-600"
                                              }`}
                >
                  {page}
                </button>
              ))}
              <button
                onClick={() =>
                  setDailyPage((p) =>
                    Math.min(dailyPagination.totalPages, p + 1)
                  )
                }
                disabled={dailyPage === dailyPagination.totalPages}
                className="px-3 py-1.5 rounded bg-gray-700 text-white text-sm
                                         disabled:opacity-50 disabled:cursor-not-allowed
                                         hover:bg-gray-600 transition-colors"
              >
                Sau ›
              </button>
            </div>
          </div>
        )}

        {/* Data Table */}
        <DataTable
          data={
            dashboardMode === "daily"
              ? filteredData.slice(
                  (dailyPage - 1) * DAILY_PAGE_SIZE,
                  dailyPage * DAILY_PAGE_SIZE
                )
              : filteredData
          }
          pageSize={dashboardMode === "daily" ? 100 : 10} // Disable internal pagination for daily
          onRowClick={
            dashboardMode === "monthly"
              ? (item) => {
                  // Extract month number from period like "T01", "T02", etc.
                  const monthMatch = item.period.match(/\d+/);
                  if (monthMatch) {
                    const monthNum = parseInt(monthMatch[0], 10);
                    handleDrilldown(monthNum, item.label);
                  }
                }
              : undefined
          }
        />
      </div>

      {/* Drilldown Modal */}
      <DrilldownModal
        isOpen={drilldown.isOpen}
        onClose={closeDrilldown}
        year={dateFilter.year}
        month={drilldown.month}
        monthLabel={drilldown.label}
      />
    </div>
  );
}
